import {User} from "../src/types";

export const users: User[] = [
    {
        id: 1,
        firstName: "Damir",
        lastName: "Lutfrakhmanov",
        maidenName: "Ramilevich",
        username: "damirlut",
        age: 18,
        gender: "male",
        email: "damirlut.dev@gmail.com",
        phone: "+7 927 94 94 164",
    },
    {
        "id": 2,
        "firstName": "Terry",
        "lastName": "Medhurst",
        "maidenName": "Smitham",
        "username": "atuny0",
        "age": 50,
        "gender": "male",
        "email": "atuny0@sohu.com",
        "phone": "+63 791 675 8914"
    },
    {
        "id": 3,
        "firstName": "Sheldon",
        "lastName": "Quigley",
        "maidenName": "Cole",
        "username": "hbingley1",
        "age": 28,
        "gender": "male",
        "email": "hbingley1@plala.or.jp",
        "phone": "+7 813 117 7139"
    },
    {
        "id": 4,
        "firstName": "Terrill",
        "lastName": "Hills",
        "maidenName": "Hoeger",
        "username": "rshawe2",
        "age": 38,
        "gender": "male",
        "email": "rshawe2@51.la",
        "phone": "+63 739 292 7942"
    },
    {
        "id": 5,
        "firstName": "Miles",
        "lastName": "Cummerata",
        "maidenName": "Maggio",
        "username": "yraigatt3",
        "age": 49,
        "gender": "male",
        "email": "yraigatt3@nature.com",
        "phone": "+86 461 145 4186"
    },
    {
        "id": 6,
        "firstName": "Mavis",
        "lastName": "Schultz",
        "maidenName": "Yundt",
        "username": "kmeus4",
        "age": 38,
        "gender": "male",
        "email": "kmeus4@upenn.edu",
        "phone": "+372 285 771 1911"
    },
    {
        "id": 7,
        "firstName": "Alison",
        "lastName": "Reichert",
        "maidenName": "Franecki",
        "username": "jtreleven5",
        "age": 21,
        "gender": "female",
        "email": "jtreleven5@nhs.uk",
        "phone": "+351 527 735 3642"
    },
    {
        "id": 8,
        "firstName": "Oleta",
        "lastName": "Abbott",
        "maidenName": "Wyman",
        "username": "dpettegre6",
        "age": 31,
        "gender": "female",
        "email": "dpettegre6@columbia.edu",
        "phone": "+62 640 802 7111"
    },
    {
        "id": 9,
        "firstName": "Ewell",
        "lastName": "Mueller",
        "maidenName": "Durgan",
        "username": "ggude7",
        "age": 29,
        "gender": "male",
        "email": "ggude7@chron.com",
        "phone": "+86 946 297 2275"
    },
    {
        "id": 10,
        "firstName": "Demetrius",
        "lastName": "Corkery",
        "maidenName": "Gleason",
        "username": "nloiterton8",
        "age": 22,
        "gender": "male",
        "email": "nloiterton8@aol.com",
        "phone": "+86 356 590 9727"
    },
    {
        "id": 11,
        "firstName": "Eleanora",
        "lastName": "Price",
        "maidenName": "Cummings",
        "username": "umcgourty9",
        "age": 37,
        "gender": "female",
        "email": "umcgourty9@jalbum.net",
        "phone": "+60 184 408 0824"
    },
    {
        "id": 12,
        "firstName": "Marcel",
        "lastName": "Jones",
        "maidenName": "Smith",
        "username": "acharlota",
        "age": 39,
        "gender": "male",
        "email": "acharlota@liveinternet.ru",
        "phone": "+967 253 210 0344"
    },
    {
        "id": 13,
        "firstName": "Assunta",
        "lastName": "Rath",
        "maidenName": "Heller",
        "username": "rhallawellb",
        "age": 42,
        "gender": "female",
        "email": "rhallawellb@dropbox.com",
        "phone": "+380 962 542 6549"
    },
    {
        "id": 14,
        "firstName": "Trace",
        "lastName": "Douglas",
        "maidenName": "Lemke",
        "username": "lgribbinc",
        "age": 26,
        "gender": "male",
        "email": "lgribbinc@posterous.com",
        "phone": "+1 609 937 3468"
    },
    {
        "id": 15,
        "firstName": "Enoch",
        "lastName": "Lynch",
        "maidenName": "Heidenreich",
        "username": "mturleyd",
        "age": 21,
        "gender": "male",
        "email": "mturleyd@tumblr.com",
        "phone": "+94 912 100 5118"
    },
    {
        "id": 16,
        "firstName": "Jeanne",
        "lastName": "Halvorson",
        "maidenName": "Cummerata",
        "username": "kminchelle",
        "age": 26,
        "gender": "female",
        "email": "kminchelle@qq.com",
        "phone": "+86 581 108 7855"
    },
    {
        "id": 17,
        "firstName": "Trycia",
        "lastName": "Fadel",
        "maidenName": "Rosenbaum",
        "username": "dpierrof",
        "age": 41,
        "gender": "female",
        "email": "dpierrof@vimeo.com",
        "phone": "+420 833 708 0340"
    },
    {
        "id": 18,
        "firstName": "Bradford",
        "lastName": "Prohaska",
        "maidenName": "Bins",
        "username": "vcholdcroftg",
        "age": 43,
        "gender": "male",
        "email": "vcholdcroftg@ucoz.com",
        "phone": "+420 874 628 3710"
    },
    {
        "id": 19,
        "firstName": "Arely",
        "lastName": "Skiles",
        "maidenName": "Monahan",
        "username": "sberminghamh",
        "age": 42,
        "gender": "male",
        "email": "sberminghamh@chron.com",
        "phone": "+55 886 766 8617"
    },
    {
        "id": 20,
        "firstName": "Gust",
        "lastName": "Purdy",
        "maidenName": "Abshire",
        "username": "bleveragei",
        "age": 46,
        "gender": "male",
        "email": "bleveragei@so-net.ne.jp",
        "phone": "+86 886 889 0258"
    },
    {
        "id": 21,
        "firstName": "Lenna",
        "lastName": "Renner",
        "maidenName": "Schumm",
        "username": "aeatockj",
        "age": 41,
        "gender": "female",
        "email": "aeatockj@psu.edu",
        "phone": "+1 904 601 7177"
    },
    {
        "id": 22,
        "firstName": "Doyle",
        "lastName": "Ernser",
        "maidenName": "Feeney",
        "username": "ckensleyk",
        "age": 23,
        "gender": "male",
        "email": "ckensleyk@pen.io",
        "phone": "+86 634 419 6839"
    },
    {
        "id": 23,
        "firstName": "Tressa",
        "lastName": "Weber",
        "maidenName": "Williamson",
        "username": "froachel",
        "age": 41,
        "gender": "female",
        "email": "froachel@howstuffworks.com",
        "phone": "+34 517 104 6248"
    },
    {
        "id": 24,
        "firstName": "Felicity",
        "lastName": "O'Reilly",
        "maidenName": "Rosenbaum",
        "username": "beykelhofm",
        "age": 46,
        "gender": "female",
        "email": "beykelhofm@wikispaces.com",
        "phone": "+63 919 564 1690"
    },
    {
        "id": 25,
        "firstName": "Jocelyn",
        "lastName": "Schuster",
        "maidenName": "Dooley",
        "username": "brickeardn",
        "age": 19,
        "gender": "male",
        "email": "brickeardn@fema.gov",
        "phone": "+7 968 462 1292"
    },
    {
        "id": 26,
        "firstName": "Edwina",
        "lastName": "Ernser",
        "maidenName": "Kiehn",
        "username": "dfundello",
        "age": 21,
        "gender": "female",
        "email": "dfundello@amazon.co.jp",
        "phone": "+86 376 986 8945"
    },
    {
        "id": 27,
        "firstName": "Griffin",
        "lastName": "Braun",
        "maidenName": "Deckow",
        "username": "lgronaverp",
        "age": 35,
        "gender": "male",
        "email": "lgronaverp@cornell.edu",
        "phone": "+62 511 790 0161"
    },
    {
        "id": 28,
        "firstName": "Piper",
        "lastName": "Schowalter",
        "maidenName": "Wuckert",
        "username": "fokillq",
        "age": 47,
        "gender": "female",
        "email": "fokillq@amazon.co.jp",
        "phone": "+60 785 960 7918"
    },
    {
        "id": 29,
        "firstName": "Kody",
        "lastName": "Terry",
        "maidenName": "Larkin",
        "username": "xisherwoodr",
        "age": 28,
        "gender": "male",
        "email": "xisherwoodr@ask.com",
        "phone": "+81 859 545 8951"
    },
    {
        "id": 30,
        "firstName": "Macy",
        "lastName": "Greenfelder",
        "maidenName": "Koepp",
        "username": "jissetts",
        "age": 45,
        "gender": "female",
        "email": "jissetts@hostgator.com",
        "phone": "+81 915 649 2384"
    },
    {
        "id": 31,
        "firstName": "Maurine",
        "lastName": "Stracke",
        "maidenName": "Abshire",
        "username": "kdulyt",
        "age": 31,
        "gender": "female",
        "email": "kdulyt@umich.edu",
        "phone": "+48 143 590 6847"
    }
]